{
 "title": "PG253",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[30s])"
    }
   ]
  },
  {
   "title": "Garbage collector",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(python_gc_collections_total[1m]))",
     "legendFormat": "collections"
    },
    {
     "expr": "sum(rate(python_gc_objects_collected_total[1m]))",
     "legendFormat": "collected per second"
    },
    {
     "expr": "sum(python_gc_objects_uncollectable_total)",
     "legendFormat": "uncollectable"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - process_start_time_seconds"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Resident" },
    { "expr": "process_virtual_memory_bytes", "legendFormat": "Virtual" }
   ]
  },
  {
   "title": "Exporter scrape duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "scrape_duration_seconds" }
   ]
  },
  {
   "title": "Open file descriptor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_open_fds / process_max_fds",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "Current transfer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "current_bytes_write", "legendFormat": "Write" },
    { "expr": "current_bytes_read", "legendFormat": "Read" }
   ]
  },
  {
   "title": "Current rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "rate(current_bytes_write[30s])", "legendFormat": "Write" },
    { "expr": "rate(current_bytes_write[30s])", "legendFormat": "Read" }
   ]
  },
  {
   "title": "Part uploaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "part_count" }
   ]
  },
  {
   "title": "All transfers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "total_bytes_write_total", "legendFormat": "Write" },
    { "expr": "total_bytes_read_total", "legendFormat": "Read" }
   ]
  },
  {
   "title": "All Current rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(total_bytes_write_total[30s])",
     "legendFormat": "Write"
    },
    {
     "expr": "rate(total_bytes_write_total[30s])",
     "legendFormat": "Read"
    }
   ]
  }
 ]
}